def register_modules(registry):
    registry.register(
        name = "drivers/xiaomi/mi_kernel_monitor",
        includes = [
            "drivers/xiaomi",
            "drivers/xiaomi/mi_kernel_monitor",
            "drivers/xiaomi/mi_kernel_monitor/kernel",
            "drivers/xiaomi/mi_kernel_monitor/mm",
            "drivers/xiaomi/mi_kernel_monitor/sched",
            "drivers/xiaomi/mi_kernel_monitor/irq",
            "drivers/xiaomi/mi_kernel_monitor/pub",
            "drivers/xiaomi/mi_kernel_monitor/locking",
            "drivers/xiaomi/mi_kernel_monitor/binder",
            "drivers/xiaomi/mi_kernel_monitor/test",
        ],
        out = "mi_kernel_monitor.ko",
        config = "CONFIG_MI_KERNEL_MONITOR",
        srcs = [
            "drivers/xiaomi/mi_kernel_monitor/entry.c",
            "drivers/xiaomi/mi_kernel_monitor/mm_tree.c",
            "drivers/xiaomi/mi_kernel_monitor/stack.c",
            "drivers/xiaomi/mi_kernel_monitor/symbol.c",
            "drivers/xiaomi/mi_kernel_monitor/misc.c",

            "drivers/xiaomi/mi_kernel_monitor/kernel/kern_entry.c",
            "drivers/xiaomi/mi_kernel_monitor/kernel/sys_cost.c",
            "drivers/xiaomi/mi_kernel_monitor/kernel/sys_delay.c",

            "drivers/xiaomi/mi_kernel_monitor/locking/locking_main.c",
            "drivers/xiaomi/mi_kernel_monitor/locking/holdlock.c",
            "drivers/xiaomi/mi_kernel_monitor/locking/holdlock_proc.c",
            "drivers/xiaomi/mi_kernel_monitor/locking/waitlock.c",
            "drivers/xiaomi/mi_kernel_monitor/locking/waitlock_sort.c",

            "drivers/xiaomi/mi_kernel_monitor/sched/sched.c",
            "drivers/xiaomi/mi_kernel_monitor/sched/preemptoff.c",
            "drivers/xiaomi/mi_kernel_monitor/sched/rt_delay.c",
            "drivers/xiaomi/mi_kernel_monitor/sched/cpu_util.c",
            "drivers/xiaomi/mi_kernel_monitor/sched/wait.c",

            ##"drivers/xiaomi/mi_kernel_monitor/irq/irq_stats.c",
            "drivers/xiaomi/mi_kernel_monitor/irq/irq_trace.c",
            "drivers/xiaomi/mi_kernel_monitor/irq/irqoff.c",

            "drivers/xiaomi/mi_kernel_monitor/pub/trace_point.c",
            "drivers/xiaomi/mi_kernel_monitor/pub/kprobe.c",
            "drivers/xiaomi/mi_kernel_monitor/pub/stack.c",
            "drivers/xiaomi/mi_kernel_monitor/pub/symbol.c",

            "drivers/xiaomi/mi_kernel_monitor/mm/mem.c",
            "drivers/xiaomi/mi_kernel_monitor/binder/binder.c", 
            "drivers/xiaomi/mi_kernel_monitor/test/test.c",

            "drivers/xiaomi/mi_kernel_monitor/internal.h",
            "drivers/xiaomi/mi_kernel_monitor/symbol.h",
            "drivers/xiaomi/mi_kernel_monitor/pub/symbol.h",
            "drivers/xiaomi/mi_kernel_monitor/pub/trace_file.h",
            "drivers/xiaomi/mi_kernel_monitor/pub/trace_point.h",
            "drivers/xiaomi/mi_kernel_monitor/pub/stack.h",
            "drivers/xiaomi/mi_kernel_monitor/pub/proc_internal.h",
            "drivers/xiaomi/mi_kernel_monitor/pub/kprobe.h",
            "drivers/xiaomi/mi_kernel_monitor/sched/cpu_util.h",
            "drivers/xiaomi/mi_kernel_monitor/sched/wait_base.h",
            "drivers/xiaomi/mi_kernel_monitor/locking/waitlock.h",
            "drivers/xiaomi/mi_kernel_monitor/locking/holdlock.h",
            "drivers/xiaomi/mi_kernel_monitor/locking/locking_main.h",
            "drivers/xiaomi/mi_kernel_monitor/mm_tree.h",
            "drivers/xiaomi/mi_kernel_monitor/kernel/kern_internal.h",
            "drivers/xiaomi/mi_kernel_monitor/uapi/irq_stats.h",
            "drivers/xiaomi/mi_kernel_monitor/uapi/irq_trace.h",
            "drivers/xiaomi/mi_kernel_monitor/uapi/kernelmonitor.h",
            "drivers/xiaomi/mi_kernel_monitor/uapi/mutex_monitor.h",
            "drivers/xiaomi/mi_kernel_monitor/uapi/pmu.h",
            "drivers/xiaomi/mi_kernel_monitor/uapi/rw_sem.h",
            "drivers/xiaomi/mi_kernel_monitor/uapi/sys_cost.h",
            "drivers/xiaomi/mi_kernel_monitor/uapi/sys_delay.h",
        ],
    )
